### ISSUE TITLE
treceback

### ISSUE THREAD

**Issue by lilnecati** [giovanni-iannaccone/ians#2]
Traceback (most recent call last):
  File "/Users/necati/ians/code/ians.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

**Comment by giovanni-iannaccone** [comment]
Hi, you have to install the requirements, to do it open the ians folder in the terminal and type:
```
chmod +x bash_file/install.sh
```
And then 
```
bash_file/install.sh
```
Now you have only to wait for the dependencies installation 👍
