### ISSUE TITLE
i am using macos

### ISSUE THREAD

**Issue by lilnecati** [giovanni-iannaccone/ians#3]
\e[0;33m [ * ] Checking for python
\e[1;31m [ X ]::[Python]: python not found
\e[0;33m [!]::[Installing Module Python...]
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

bash_file/install.sh: line 29: pip2: command not found
\e[0;33m [ * ] Installing requirements
bash_file/install.sh: line 34: pip: command not found
\e[34m [ ✔ ] Requirements installed
\e[34m Done, press ENTER to continue

**Comment by giovanni-iannaccone** [comment]
## Sorry but you must use linux 🐧
it should work also on windows 🪟 but i forgot to add macos 🍏. Install linux in dual boot or on a virtual machine and you won't have any problem
