### ISSUE TITLE
internet connection issue

### ISSUE THREAD

**Issue by jash69** [giovanni-iannaccone/ians#4]
██████╗██╗  ██╗███████╗ ██████╗██╗  ██╗██╗███╗   ██╗ ██████╗
  ██╔════╝██║  ██║██╔════╝██╔════╝██║ ██╔╝██║████╗  ██║██╔════╝
  ██║     ███████║█████╗  ██║     █████╔╝ ██║██╔██╗ ██║██║  ███╗
  ██║     ██╔══██║██╔══╝  ██║     ██╔═██╗ ██║██║╚██╗██║██║   ██║
  ╚██████╗██║  ██║███████╗╚██████╗██║  ██╗██║██║ ╚████║╚██████╔╝██╗██╗██╗
   ╚═════╝╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝╚═╝╚═╝

 -------------------------- Giovanni Iannaccone --------------------------

 [ * ] Checking for root user
 [User: root]
 [ ✔ ]::[User]: ROOT
 [ * ] Checking for internet connection
 [ X ]::[Internet Connection]: OFFLINE!

**Comment by jash69** [comment]
> You must be connected to use ians, check your connection and try another time

i was connected, and yet it showed this.

**Comment by giovanni-iannaccone** [comment]
Which os are you using ?

**Comment by jash69** [comment]
i was using kali linux as wsl

**Comment by giovanni-iannaccone** [comment]
## Try to install it on a virtual machine and it will work 🐉

**Comment by jash69** [comment]
> ## Try to install it on a virtual machine and it will work 🐉
> Tomorrow i'll add a feature to make it work also on windows

hi, did you add a feature of windows yet?

**Comment by giovanni-iannaccone** [comment]
Yes, but maybe some modules won't work
